name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE_NAME: tycho-devbox
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: |
        docker login -u ${{ env.DOCKER_USERNAME}} -p ${{ env.DOCKER_PASSWORD}} 

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:${{ github.sha }} --tag ${{env.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:latest
      
    - name: Push image to Docker Hub
      run: |
        docker push ${{env.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{env.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:latest